# Generated by Django 5.1.4 on 2025-01-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_type_rename_stock_product_quantity_stockmovement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='user',
        ),
    ]
