# Generated by Django 5.1.4 on 2025-01-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_quantity_product_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='quantity',
        ),
    ]
